version: "3.5"
services:

  chroma-db:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - chroma-net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  chroma-net: